services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    tty: true
    image: input-attendance
    container_name: input-attendance-container
    environment:
      TZ: 'Asia/Tokyo'
    network_mode: 'host'
